### ISSUE TITLE
Newbie: Cannot replicate the speed of sampling on very new hardware, significant difference. 

### ISSUE THREAD

**Issue by rudnirol** [pymc-labs/research#8]
The speed differs significantly from my pip environment to (base) conda environment with conda being significantly faster when trying to replicate do-operators notebook. However, it is nowhere near the 2 seconds sampling time indicated in the said notebook, it takes my AMD Ryzen 9 5900X (24) @ 3.700GHz 132 seconds to do the same. I would appreciate if you could point out possible shortcomings: is it my hardware that is so much slower or there needs to be environment changes done. Thanks!

**Comment by twiecki** [comment]
`pip` installation is not supported. With AMD you probably can't run the intel MKL blas? That could be it. You can try running `nutpie`.

**Comment by rudnirol** [comment]
Thanks for quick response and tips, I very much appreciate it.
